#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare foobar2000 for snap
#
# Date: Jan 24 2018
#

chkver () {
    wget http://www.foobar2000.org/download -q -S -O - 2>&1 | cat download | grep foobar2000_v | awk '{print $4}'|sed 2d|sed 's|v||;s|</a><br||'
}

chkArch () {
    uname -m | grep x86_64 | wc -l
}

chkosn () {
    lsb_release -sc
}

chk7z16 () {
    apt list --installed 2>&1 | grep p7zip | grep "16.02" | wc -l
}

chkexe () {
    find -iname 'foobar2000*.exe' | wc -l
}

dlf2k () {
    wget https://www.foobar2000.org/download -nH --cut-dirs=3 -r -l 2 -A exe -R '*beta*.exe' &> /dev/null
}

dli7z16x86 () {
    for dldebs in https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091329/+files/p7zip_16.02+dfsg-4_i386.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091329/+files/p7zip-full_16.02+dfsg-4_i386.deb
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in p7zip_16.02+dfsg-4_i386.deb p7zip-full_16.02+dfsg-4_i386.deb
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

dli7z16x64 () {
    for dldebs in https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb 
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

mkf2k () {
    7z x "foobar2000_v*.exe" -x'!$PLUGINSDIR' -x'!$R0' -x'!icons' -x'!foobar2000 Shell Associations Updater.exe' -x'!uninstall.exe' -o"usr/share/foobar2000" &> /dev/null
    touch usr/share/foobar2000/portable_mode_enabled
    find "usr" -type d -execdir chmod 755 {} +
}

mkall () {
    if [ $(chkexe) -eq 0 ]; then
        dlf2k
        if [ $(chkosn) == "xenial" ]; then
            if [ $(chk7z16) -eq 0 ]; then
                if [ $(chkArch) -eq 1 ]; then
                    dli7z16x64
                elif [ $(chkArch) -eq 0 ]; then
                    dli7z16x86
                fi
            fi
        fi
    fi
        mkf2k
}

mkall
mkdir bin && cp ./foobar2000 bin && mkdir -p usr/share/applications && cp ../../../snap/gui/foobar2000.desktop usr/share/applications
rm foobar2000*.exe dl_f2k  foobar2000  foobar2000.png  LICENSE.md README.md