#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare foobar2000 for snap
#
# Date: Jan 24 2018
#

dlf2k () {
    wget https://www.foobar2000.org/download -nH --cut-dirs=3 -r -l 2 -A exe -R '*beta*.exe' &> /dev/null
    for fnts in andalemo.ttf arialbd.ttf arialbi.ttf ariali.ttf arial.ttf ariblk.ttf comicbd.ttf comic.ttf courbd.ttf courbi.ttf couri.ttf cour.ttf georgiab.ttf georgiai.ttf georgia.ttf georgiaz.ttf impact.ttf l_10646.ttf lucon.ttf micross.ttf symbol.ttf tahomabd.ttf tahoma.ttf timesbd.ttf timesbi.ttf timesi.ttf times.ttf trebucbd.ttf trebucbi.ttf trebucit.ttf trebuc.ttf verdanab.ttf verdanai.ttf verdana.ttf verdanaz.ttf webdings.ttf wingding.ttf
    do
    wget https://github.com/caarlos0-graveyard/msfonts/blob/master/fonts/$fnts?raw=true -P share/wine/fonts &> /dev/null
    mv share/wine/fonts/$fnts?raw=true share/wine/fonts/$fnts
    done
}

dli7z16x64 () {
    for dldebs in https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb 
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

mkf2k () {
    7z x "foobar2000_v*.exe" -x'!$PLUGINSDIR' -x'!$R0' -x'!icons' -x'!foobar2000 Shell Associations Updater.exe' -x'!uninstall.exe' -o"usr/share/foobar2000" &> /dev/null
    touch usr/share/foobar2000/portable_mode_enabled
    find "usr" -type d -execdir chmod 755 {} +
    mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
    wrestool -x -t3 -n5 usr/share/foobar2000/foobar2000.exe --raw > usr/share/pixmaps/foobar2000.png
}

mkdsk () {
cat > foobar2000.desktop <<'EOF1'
[Desktop Entry]
Name=foobar2000
GenericName=Audio player
Comment=Simple and powerful audio player.
Actions=PlayPause;Stop;Next;Prev;Random;Config
Encoding=UTF-8
Version=1.3.17
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/foobar2000.png
TryExec=foobar2000
Exec=foobar2000 -immediate %F
StartupWMClass=foobar2000.exe
Categories=AudioVideo;Audio;Player;
MimeType=audio/aac;audio/x-ape;audio/basic;audio/mp4;audio/mpeg;audio/mpegurl;audio/vorbis;audio/x-flac;audio/x-mp2;audio/x-mp3;audio/x-mpegurl;audio/x-ms-wma;audio/x-oggflac;audio/x-speex;audio/x-vorbis;audio/x-wav;audio/m3u;audio/x-aifc;audio/x-aiffc;audio/x-aiff;audio/x-musepack;audio/x-wavpack;x-content/audio-player;audio/x-matroska;audio/x-vorbis+ogg;

[Desktop Action PlayPause]
Name=Play/Pause
Exec=foobar2000 -playpause

[Desktop Action Stop]
Name=Stop
Exec=foobar2000 -stop

[Desktop Action Next]
Name=Next
Exec=foobar2000 -next

[Desktop Action Prev]
Name=Prev
Exec=foobar2000 -prev

[Desktop Action Random]
Name=Random
Exec=foobar2000 -rand

[Desktop Action Config]
Name=Preferences
Exec=foobar2000 -config
EOF1
}

dlf2k
dli7z16x64
mkdsk
mkf2k
mv foobar2000 bin && mv foobar2000.desktop usr/share/applications
rm foobar2000*.exe dl_f2k