#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   foobar2000 wrapper for snap
#
# Date: Jan 24 2018
#

ARCH="i386-linux-gnu"

export WINEVERPATH=$SNAP
export PATH=$SNAP/bin:$SNAP/usr:bin:$PATH 
export WINESERVER=$SNAP/bin/wineserver
export WINELOADER=$SNAP/bin/wine
export WINEDLLPATH=$SNAP/lib/wine/fakedlls
export WINEPREFIX=$SNAP_USER_COMMON/.wine
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG=-all
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/lib/$ARCH:$SNAP/usr/lib:$SNAP/usr/lib/$ARCH:$SNAP/usr/lib/$ARCH/pulseaudio:$LD_LIBRARY_PATH"

export HOME=$SNAP_USER_COMMON
export XDG_DATA_HOME=$SNAP_USER_COMMON/usr/share
export REALHOME=`getent passwd $UID | cut -d ':' -f 6`

# Check current desktop
CCD=$(env | grep '^XDG_CURRENT_DESKTOP=' | awk -F'=' '{print $2}')

# Check gtk3 theme on kde
CGTK=$(grep '^gtk-theme-name=' $REALHOME/.config/gtk-3.0/settings.ini 2>/dev/null | awk -F'=' '{print $2}')

# foobar2000 env
progName=foobar2000
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe
progUiFix=$progHome/configuration/foo_ui_std.dll.cfg
progReg=$progHome/xp.reg

if [ ! -d $progHome ];then
mkdir -p $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &>/dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &>/dev/null

# fix ui glitch - workaround bug ui not showing of foobar2000 on wine.
if [ -f $progUiFix ]; then
rm "$progUiFix"
fi

if [ ! -d $WINEPREFIX ]; then
mkdir -p $WINEPREFIX/drive_c/windows/Fonts
find /usr/share/fonts/ -type f -name "*.ttf" -exec ln -vs "{}" $WINEPREFIX/drive_c/windows/Fonts/ \; &>/dev/null
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion]
"CSDVersion"="Service Pack 3"
"CurrentBuildNumber"="2600"
"CurrentVersion"="5.1"
"ProductName"="Microsoft Windows XP"

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows]
"CSDVersion"=dword:00000300
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CCD == "KDE" ]; then
if [ $CGTK == "Breeze" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="239 240 241"
"ActiveTitle"="239 240 241"
"AppWorkspace"="239 240 241"
"Background"="239 240 241"
"ButtonAlternateFace"="239 240 241"
"ButtonDkShadow"="239 240 241"
"ButtonFace"="239 240 241"
"ButtonHilight"="239 240 241"
"ButtonLight"="192 194 196"
"ButtonShadow"="192 194 196"
"ButtonText"="49 54 59"
"GradientActiveTitle"="239 240 241"
"GradientInActiveTitle"="239 240 241"
"GrayText"="45 49 54"
"Hilight"="61 174 233"
"HilightText"="239 240 241"
"HotTrackingColor"="61 174 233"
"InActiveBorder"="239 240 241"
"InActiveTitle"="239 240 241"
"InActiveTitleText"="45 49 54"
"InfoText"="49 54 59"
"InfoWindow"="239 240 241"
"Menu"="239 240 241"
"MenuBar"="61 174 233"
"MenuHilight"="239 240 241"
"MenuText"="49 54 59"
"Scrollbar"="239 240 241"
"TitleText"="49 54 59"
"Window"="252 252 252"
"WindowFrame"="239 240 241"
"WindowText"="49 54 59"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Breeze-Dark" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="49 54 59"
"ActiveTitle"="49 54 59"
"AppWorkspace"="49 54 59"
"Background"="49 54 59"
"ButtonAlternateFace"="49 54 59"
"ButtonDkShadow"="49 54 59"
"ButtonFace"="49 54 59"
"ButtonHilight"="49 54 59"
"ButtonLight"="97 101 105"
"ButtonShadow"="97 101 105"
"ButtonText"="239 240 241"
"GradientActiveTitle"="49 54 59"
"GradientInActiveTitle"="49 54 59"
"GrayText"="216 218 221"
"Hilight"="61 174 233"
"HilightText"="239 240 241"
"HotTrackingColor"="61 174 233"
"InActiveBorder"="49 54 59"
"InActiveTitle"="49 54 59"
"InActiveTitleText"="216 218 221"
"InfoText"="239 240 241"
"InfoWindow"="49 54 59"
"Menu"="49 54 59"
"MenuBar"="61 174 233"
"MenuHilight"="49 54 59"
"MenuText"="239 240 241"
"Scrollbar"="49 54 59"
"TitleText"="239 240 241"
"Window"="35 38 41"
"WindowFrame"="49 54 59"
"WindowText"="239 240 241"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Emacs" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="233 233 233"
"ActiveTitle"="233 233 233"
"AppWorkspace"="233 233 233"
"Background"="233 233 233"
"ButtonAlternateFace"="233 233 233"
"ButtonDkShadow"="233 233 233"
"ButtonFace"="233 233 233"
"ButtonHilight"="233 233 233"
"ButtonLight"="161 161 161"
"ButtonShadow"="161 161 161"
"ButtonText"="46 52 54"
"GradientActiveTitle"="233 233 233"
"GradientInActiveTitle"="233 233 233"
"GrayText"="141 144 145"
"Hilight"="74 144 217"
"HilightText"="255 255 255"
"HotTrackingColor"="74 144 217"
"InActiveBorder"="233 233 233"
"InActiveTitle"="233 233 233"
"InActiveTitleText"="141 144 145"
"InfoText"="46 52 54"
"InfoWindow"="233 233 233"
"Menu"="233 233 233"
"MenuBar"="74 144 217"
"MenuHilight"="212 208 200"
"MenuText"="46 52 54"
"Scrollbar"="233 233 233"
"TitleText"="46 52 54"
"Window"="255 255 255"
"WindowFrame"="233 233 233"
"WindowText"="46 52 54"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Arc" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="245 246 247"
"ActiveTitle"="245 246 247"
"AppWorkspace"="245 246 247"
"Background"="245 246 247"
"ButtonAlternateFace"="245 246 247"
"ButtonDkShadow"="245 246 247"
"ButtonFace"="245 246 247"
"ButtonHilight"="245 246 247"
"ButtonLight"="220 223 227"
"ButtonShadow"="220 223 227"
"ButtonText"="59 62 69"
"GradientActiveTitle"="245 246 247"
"GradientInActiveTitle"="245 246 247"
"GrayText"="59 62 69"
"Hilight"="82 148 226"
"HilightText"="255 255 255"
"HotTrackingColor"="82 148 226"
"InActiveBorder"="245 246 247"
"InActiveTitle"="245 246 247"
"InActiveTitleText"="59 62 69"
"InfoText"="59 62 69"
"InfoWindow"="245 246 247"
"Menu"="245 246 247"
"MenuBar"="82 148 226"
"MenuHilight"="231 232 235"
"MenuText"="53 59 75"
"Scrollbar"="245 246 247"
"TitleText"="59 62 69"
"Window"="255 255 255"
"WindowFrame"="245 246 247"
"WindowText"="59 62 69"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Arc-Dark" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="56 60 74"
"ActiveTitle"="56 60 74"
"AppWorkspace"="56 60 74"
"Background"="56 60 74"
"ButtonAlternateFace"="56 60 74"
"ButtonDkShadow"="56 60 74"
"ButtonFace"="56 60 74"
"ButtonHilight"="56 60 74"
"ButtonLight"="43 46 57"
"ButtonShadow"="43 46 57"
"ButtonText"="211 218 227"
"GradientActiveTitle"="56 60 74"
"GradientInActiveTitle"="56 60 74"
"GrayText"="211 218 227"
"Hilight"="82 148 226"
"HilightText"="255 255 255"
"HotTrackingColor"="82 148 226"
"InActiveBorder"="56 60 74"
"InActiveTitle"="56 60 74"
"InActiveTitleText"="211 218 227"
"InfoText"="211 218 227"
"InfoWindow"="56 60 74"
"Menu"="56 60 74"
"MenuBar"="82 148 226"
"MenuHilight"="47 52 63"
"MenuText"="207 218 231"
"Scrollbar"="56 60 74"
"TitleText"="211 218 227"
"Window"="64 69 82"
"WindowFrame"="56 60 74"
"WindowText"="211 218 227"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Materia-light" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="242 242 242"
"ActiveTitle"="242 242 242"
"AppWorkspace"="242 242 242"
"Background"="242 242 242"
"ButtonAlternateFace"="242 242 242"
"ButtonDkShadow"="242 242 242"
"ButtonFace"="242 242 242"
"ButtonHilight"="242 242 242"
"ButtonLight"="0 0 0"
"ButtonShadow"="0 0 0"
"ButtonText"="0 0 0"
"GradientActiveTitle"="242 242 242"
"GradientInActiveTitle"="242 242 242"
"GrayText"="0 0 0"
"Hilight"="66 133 244"
"HilightText"="255 255 255"
"HotTrackingColor"="66 133 244"
"InActiveBorder"="242 242 242"
"InActiveTitle"="242 242 242"
"InActiveTitleText"="0 0 0"
"InfoText"="0 0 0"
"InfoWindow"="242 242 242"
"Menu"="242 242 242"
"MenuBar"="66 133 244"
"MenuHilight"="224 224 224"
"MenuText"="0 0 0"
"Scrollbar"="242 242 242"
"TitleText"="0 0 0"
"Window"="255 255 255"
"WindowFrame"="242 242 242"
"WindowText"="0 0 0"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Materia-dark" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="40 40 40"
"ActiveTitle"="40 40 40"
"AppWorkspace"="40 40 40"
"Background"="40 40 40"
"ButtonAlternateFace"="40 40 40"
"ButtonDkShadow"="40 40 40"
"ButtonFace"="40 40 40"
"ButtonHilight"="40 40 40"
"ButtonLight"="0 0 0"
"ButtonShadow"="0 0 0"
"ButtonText"="255 255 255"
"GradientActiveTitle"="40 40 40"
"GradientInActiveTitle"="40 40 40"
"GrayText"="255 255 255"
"Hilight"="66 133 244"
"HilightText"="255 255 255"
"HotTrackingColor"="66 133 244"
"InActiveBorder"="40 40 40"
"InActiveTitle"="40 40 40"
"InActiveTitleText"="255 255 255"
"InfoText"="255 255 255"
"InfoWindow"="40 40 40"
"Menu"="40 40 40"
"MenuBar"="66 133 244"
"MenuHilight"="56 56 56"
"MenuText"="255 255 255"
"Scrollbar"="40 40 40"
"TitleText"="255 255 255"
"Window"="48 48 48"
"WindowFrame"="40 40 40"
"WindowText"="255 255 255"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Adapta" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="250 251 252"
"ActiveTitle"="250 251 252"
"AppWorkspace"="250 251 252"
"Background"="250 251 252"
"ButtonAlternateFace"="250 251 252"
"ButtonDkShadow"="250 251 252"
"ButtonFace"="250 251 252"
"ButtonHilight"="250 251 252"
"ButtonLight"="0 0 0"
"ButtonShadow"="0 0 0"
"ButtonText"="38 50 56"
"GradientActiveTitle"="250 251 252"
"GradientInActiveTitle"="250 251 252"
"GrayText"="38 50 56"
"Hilight"="0 188 212"
"HilightText"="255 255 255"
"HotTrackingColor"="0 188 212"
"InActiveBorder"="250 251 252"
"InActiveTitle"="250 251 252"
"InActiveTitleText"="38 50 56"
"InfoText"="38 50 56"
"InfoWindow"="250 251 252"
"Menu"="253 253 254"
"MenuBar"="0 188 212"
"MenuHilight"="34 45 50"
"MenuText"="34 45 50"
"Scrollbar"="250 251 252"
"TitleText"="38 50 56"
"Window"="255 255 255"
"WindowFrame"="250 251 252"
"WindowText"="38 50 56"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if [ $CGTK == "Adapta-Nokto" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="38 50 56"
"ActiveTitle"="38 50 56"
"AppWorkspace"="38 50 56"
"Background"="38 50 56"
"ButtonAlternateFace"="38 50 56"
"ButtonDkShadow"="38 50 56"
"ButtonFace"="38 50 56"
"ButtonHilight"="38 50 56"
"ButtonLight"="0 0 0"
"ButtonShadow"="0 0 0"
"ButtonText"="207 216 220"
"GradientActiveTitle"="38 50 56"
"GradientInActiveTitle"="38 50 56"
"GrayText"="207 216 220"
"Hilight"="0 188 212"
"HilightText"="255 255 255"
"HotTrackingColor"="0 188 212"
"InActiveBorder"="38 50 56"
"InActiveTitle"="38 50 56"
"InActiveTitleText"="207 216 220"
"InfoText"="207 216 220"
"InfoWindow"="38 50 56"
"Menu"="40 52 58"
"MenuBar"="0 188 212"
"MenuHilight"="34 45 50"
"MenuText"="207 216 220"
"Scrollbar"="38 50 56"
"TitleText"="207 216 220"
"Window"="34 45 50"
"WindowFrame"="38 50 56"
"WindowText"="207 216 220"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi
else
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="212 208 200"
"ActiveTitle"="0 84 227"
"AppWorkSpace"="128 128 128"
"Background"="0 78 152"
"ButtonAlternateFace"="181 181 181"
"ButtonDkShadow"="113 111 100"
"ButtonFace"="236 233 216"
"ButtonHilight"="255 255 255"
"ButtonLight"="241 239 226"
"ButtonShadow"="172 168 153"
"ButtonText"="0 0 0"
"GradientActiveTitle"="61 149 255"
"GradientInactiveTitle"="157 185 235"
"GrayText"="172 168 153"
"Hilight"="49 106 197"
"HilightText"="255 255 255"
"HotTrackingColor"="0 0 200"
"InactiveBorder"="212 208 200"
"InactiveTitle"="122 150 223"
"InactiveTitleText"="216 228 248"
"InfoText"="0 0 0"
"InfoWindow"="255 255 225"
"Menu"="236 233 216"
"MenuBar"="49 106 197"
"MenuHilight"="236 233 216"
"MenuText"="0 0 0"
"Scrollbar"="212 208 200"
"TitleText"="255 255 255"
"Window"="255 255 255"
"WindowFrame"="0 0 0"
"WindowText"="0 0 0"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

# Stop WINE from updating $WINEPREFIX automatically 
if [ -f $WINEPREFIX/.update-timestamp ]; then
chkstmp=$(cat $WINEPREFIX/.update-timestamp | grep disable | wc -l)
    if [ $chkstmp -eq 0 ]; then
        echo "disable" > "$WINEPREFIX/.update-timestamp"
    fi
fi

# Switches: use -something instead of /something to avoid confusion with Unix paths
# Also convert Unix paths to Windows paths.
declare -a args

for arg; do
    if [[ "${arg:0:1}" = "-" ]]; then
        args+=("${arg/#-//}")
    else
        args+=("$(winepath -w "$arg")")
    fi
done

if [ -z "$1" ] ; then
  wine "$progHome/$progBin"
else
  wine start /unix "$progHome/$progBin" "${args[@]}"
fi
