#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare foobar2000 for snap
#
# Date: Jan 24 2018
#

dlf2k () {
    wget https://www.foobar2000.org/download -nH --cut-dirs=3 -r -l 2 -A exe -R '*beta*.exe' &> /dev/null
}

dli7z16x64 () {
    for dldebs in https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb 
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

mkf2k () {
    mkdir ./{wine-platform,bin} && mkdir -p usr/share/{pixmaps,applications}
    7z x "foobar2000_v*.exe" -x'!$PLUGINSDIR' -x'!$R0' -x'!icons' -x'!foobar2000 Shell Associations Updater.exe' -x'!uninstall.exe' -o"usr/share/foobar2000" &> /dev/null
    touch usr/share/foobar2000/portable_mode_enabled
    find "usr" -type d -execdir chmod 755 {} +
}

mkdsk () {
ver=$(wget http://www.foobar2000.org/download -q -S -O - 2>&1 | grep foobar2000_v | awk '{print $4}'|sed '2,3d;s|v||;s|</a><br||;s|</a>||')
cat > foobar2000.desktop <<'EOF1'
[Desktop Entry]
Name=foobar2000
GenericName=Audio player
Comment=Simple and powerful audio player.
Actions=PlayPause;Stop;Next;Prev;Random;Config
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/foobar2000.png
TryExec=foobar2000
Exec=foobar2000 -immediate %F
StartupWMClass=foobar2000.exe
Categories=AudioVideo;Audio;Player;
MimeType=audio/aac;audio/x-ape;audio/basic;audio/mp4;audio/mpeg;audio/mpegurl;audio/vorbis;audio/x-flac;audio/x-mp2;audio/x-mp3;audio/x-mpegurl;audio/x-ms-wma;audio/x-oggflac;audio/x-speex;audio/x-vorbis;audio/x-wav;audio/m3u;audio/x-aifc;audio/x-aiffc;audio/x-aiff;audio/x-musepack;audio/x-wavpack;x-content/audio-player;audio/x-matroska;audio/x-vorbis+ogg;

[Desktop Action PlayPause]
Name=Play/Pause
Exec=foobar2000 -playpause

[Desktop Action Stop]
Name=Stop
Exec=foobar2000 -stop

[Desktop Action Next]
Name=Next
Exec=foobar2000 -next

[Desktop Action Prev]
Name=Prev
Exec=foobar2000 -prev

[Desktop Action Random]
Name=Random
Exec=foobar2000 -rand

[Desktop Action Config]
Name=Preferences
Exec=foobar2000 -config
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' foobar2000.desktop
}

dlf2k
dli7z16x64
mkdsk
mkf2k
mv foobar2000 bin && mv foobar2000.desktop usr/share/applications && mv foobar2000.png usr/share/pixmaps && cp -R -p {bin,usr,wine-platform} $SNAPCRAFT_PART_INSTALL